categorias = [
    'Camisetas',
    'Regatas',
    'Camisas sociais',
    'Camisas polo',
    'Blusas de frio',
    'Moletons',
    'Jaquetas',
    'Casacos',
    'Ternos e blazers',
    'Calças jeans',
    'Calças sociais',
    'Calças jogger',
    'Bermudas',
    'Shorts',
    'Saias',
    'Vestidos casuais',
    'Vestidos de festa',
    'Macacões',
    'Conjuntos femininos',
    'Conjuntos masculinos',
    'Roupas infantis',
    'Moda plus size',
    'Moda fitness',
    'Moda praia',
    'Moda íntima',
    'Lingerie',
    'Pijamas',
    'Meias',
    'Bonés e chapéus',
    'Luvas',
    'Cachecóis',
    'Roupas para gestantes',
    'Uniformes escolares',
    'Uniformes profissionais',
]